import type { Metadata } from "next";
import '../styles/globals.css';
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import localFont from "next/font/local";
import { ReactNode } from "react";

const SFPro = localFont({
    src: '../../public/font/sf-pro/SFPRODISPLAYMEDIUM.otf',
    variable: '--font-sf-pro',
    display: 'swap',
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type Locale = "en" | "az" | "ru";

export default function RootLayout({
    children,
    params,
}: {
    children: any;
    params: any;
}) {
    console.log(params.locale);

    return (
        <html lang={params.locale}>
            <body className={`antialiased ${SFPro.variable}`}>
                {children}
            </body>
        </html>
    );
}