import type { Metadata } from "next";
import '../styles/globals.css';
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import localFont from "next/font/local";

const SFPro = localFont({
    src: '../../public/font/sf-pro/SFPRODISPLAYMEDIUM.otf',
    variable: '--font-sf-pro',
    display: 'swap',
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
    params: Promise<{ locale: "az" | "en" | "ru" }>;
}>) {
    return (
        <html lang="en">
            <body className={`${SFPro.variable} antialiased`}>
                {children}
            </body>
        </html>
    );
}
