import type { Metadata } from "next";
import '../styles/globals.css';
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import localFont from "next/font/local";

const SFPro = localFont({
    src: '../../public/font/sf-pro/SFPRODISPLAYMEDIUM.otf',
    variable: '--font-sf-pro',
    display: 'swap',
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
    params,
}: Readonly<{
    children: any;
    params: any;
}>) {
    const resolvedParams = await params;
    const { locale } = resolvedParams
    console.log(locale);
        
    return (
        <html lang={resolvedParams.locale}>
            <body className="antialiased">
                {children}
            </body>
        </html>
    );
}
